-- --------------------------------------------------------
-- Host:                         127.0.0.1
-- Server version:               11.2.0-MariaDB - mariadb.org binary distribution
-- Server OS:                    Win64
-- HeidiSQL Version:             12.3.0.6589
-- --------------------------------------------------------

/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET NAMES utf8 */;
/*!50503 SET NAMES utf8mb4 */;
/*!40103 SET @OLD_TIME_ZONE=@@TIME_ZONE */;
/*!40103 SET TIME_ZONE='+00:00' */;
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;
/*!40111 SET @OLD_SQL_NOTES=@@SQL_NOTES, SQL_NOTES=0 */;


-- Dumping database structure for works
CREATE DATABASE IF NOT EXISTS `works` /*!40100 DEFAULT CHARACTER SET latin1 COLLATE latin1_swedish_ci */;
USE `works`;

-- Dumping structure for table works.address
CREATE TABLE IF NOT EXISTS `address` (
  `id` bigint(20) NOT NULL AUTO_INCREMENT,
  `street` varchar(150) DEFAULT NULL,
  `city` varchar(50) DEFAULT NULL,
  `country` smallint(6) DEFAULT NULL CHECK (`country` between 0 AND 999),
  `number` varchar(20) DEFAULT NULL,
  `zipcode` varchar(7) DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1 COLLATE=latin1_swedish_ci;

-- Data exporting was unselected.
INSERT INTO `address` (`street`, `city`, `country`, `number`, `zipcode`) VALUES
('Main Street', 'New York', 704, '101', '10001'),
('Broadway', 'Los Angeles', 40, '102', '90001'),
('High Street', 'Chicago', 840, '103', '60601'),
('Elm Street', 'Houston', 826, '104', '77001'),
('Oak Avenue', 'Phoenix', 336, '105', '85001'),
('Maple Drive', 'Philadelphia', 76, '106', '19101'),
('Pine Lane', 'San Antonio', 124, '107', '78201'),
('Cedar Road', 'San Diego', 156, '108', '92101'),
('Willow Path', 'Dallas', 192, '109', '75201'),
('Cherry Blvd', 'San Jose', 724, '110', '95101'),
('Birch Street', 'Austin', 704, '111', '73301'),
('Walnut Ave', 'Jacksonville', 40, '112', '32201'),
('Poplar Way', 'Fort Worth', 840, '113', '76101'),
('Aspen Lane', 'Columbus', 826, '114', '43085'),
('Spruce Street', 'San Francisco', 336, '115', '94101'),
('Magnolia Drive', 'Charlotte', 76, '116', '28201'),
('Holly Avenue', 'Indianapolis', 124, '117', '46201'),
('Sycamore Lane', 'Seattle', 156, '118', '98101'),
('Dogwood Road', 'Denver', 192, '119', '80201'),
('Chestnut Blvd', 'Washington', 724, '120', '20001'),
('Ash Way', 'Boston', 704, '121', '02101'),
('Juniper Path', 'El Paso', 40, '122', '79901'),
('Fir Avenue', 'Detroit', 840, '123', '48201'),
('Cypress Road', 'Nashville', 826, '124', '37201'),
('Palm Street', 'Memphis', 336, '125', '37501'),
('Olive Lane', 'Portland', 76, '126', '97086'),
('Laurel Ave', 'Oklahoma City', 124, '127', '73101'),
('Beech Path', 'Las Vegas', 156, '128', '89101'),
('Linden Blvd', 'Baltimore', 192, '129', '21201'),
('Cottonwood Drive', 'Louisville', 724, '130', '40201'),
('Hickory Lane', 'Milwaukee', 704, '131', '53201'),
('Sequoia Street', 'Albuquerque', 40, '132', '87101'),
('Redwood Avenue', 'Tucson', 840, '133', '85701'),
('Aspen Blvd', 'Fresno', 826, '134', '93650'),
('Elmwood Lane', 'Sacramento', 336, '135', '94203'),
('Willow Drive', 'Kansas City', 76, '136', '64101'),
('Maple Path', 'Atlanta', 124, '137', '30301'),
('Cherry Road', 'Miami', 156, '138', '33101'),
('Magnolia Blvd', 'Oakland', 192, '139', '94601'),
('Walnut Path', 'Tulsa', 724, '140', '74101'),
('Poplar Drive', 'Minneapolis', 704, '141', '55401'),
('Birch Road', 'Arlington', 40, '142', '76001'),
('Spruce Lane', 'New Orleans', 840, '143', '70112'),
('Sycamore Street', 'Wichita', 826, '144', '67201'),
('Chestnut Ave', 'Cleveland', 336, '145', '44101'),
('Pine Way', 'Tampa', 76, '146', '33601'),
('Cedar Blvd', 'Aurora', 124, '147', '80010'),
('Holly Lane', 'Anaheim', 156, '148', '92801'),
('Aspen Drive', 'Honolulu', 192, '149', '96801'),
('Oak Path', 'Lexington', 724, '150', '40502'),
('Willow Lane', 'Stockton', 704, '151', '95201'),
('Maple Street', 'Henderson', 40, '152', '89002'),
('Cherry Ave', 'Riverside', 840, '153', '92501'),
('Magnolia Path', 'Corpus Christi', 826, '154', '78401'),
('Walnut Blvd', 'St. Louis', 336, '155', '63101'),
('Dogwood Drive', 'Pittsburgh', 76, '156', '15201'),
('Birch Way', 'Cincinnati', 124, '157', '45201'),
('Poplar Lane', 'Anchorage', 156, '158', '99501'),
('Aspen Ave', 'Orlando', 192, '159', '32801'),
('Elm Street', 'Buffalo', 724, '160', '14201'),
('Cypress Drive', 'Reno', 704, '161', '89501'),
('Palm Lane', 'Boise', 40, '162', '83701'),
('Juniper Road', 'Chandler', 840, '163', '85224'),
('Hickory Blvd', 'Lubbock', 826, '164', '79401'),
('Linden Drive', 'Scottsdale', 336, '165', '85251'),
('Olive Path', 'Madison', 76, '166', '53701'),
('Beech Lane', 'Laredo', 124, '167', '78040'),
('Sequoia Avenue', 'Durham', 156, '168', '27701'),
('Redwood Blvd', 'Chula Vista', 192, '169', '91910'),
('Elmwood Drive', 'Fort Wayne', 724, '170', '46801'),
('Willow Road', 'Jersey City', 704, '171', '07097'),
('Oak Street', 'Chattanooga', 40, '172', '37401'),
('Maple Blvd', 'Greensboro', 840, '173', '27401'),
('Cherry Path', 'St. Paul', 826, '174', '55101'),
('Magnolia Ave', 'Lincoln', 336, '175', '68501'),
('Walnut Drive', 'Plano', 76, '176', '75023'),
('Poplar Blvd', 'Anchorage', 124, '177', '99501'),
('Birch Path', 'Newark', 156, '178', '07101'),
('Spruce Drive', 'Toledo', 192, '179', '43601'),
('Chestnut Path', 'Orlando', 724, '180', '32801'),
('Cypress Blvd', 'Buffalo', 704, '181', '14201'),
('Palm Street', 'Reno', 40, '182', '89501'),
('Juniper Ave', 'Boise', 840, '183', '83701'),
('Hickory Lane', 'Chandler', 826, '184', '85224'),
('Linden Street', 'Lubbock', 336, '185', '79401'),
('Olive Blvd', 'Scottsdale', 76, '186', '85251'),
('Beech Drive', 'Madison', 124, '187', '53701'),
('Sequoia Path', 'Laredo', 156, '188', '78040'),
('Redwood Lane', 'Durham', 192, '189', '27701'),
('Elmwood Street', 'Chula Vista', 724, '190', '91910'),
('Willow Avenue', 'Fort Wayne', 704, '191', '46801'),
('Oak Path', 'Jersey City', 40, '192', '07097'),
('Maple Lane', 'Chattanooga', 840, '193', '37401'),
('Cherry Road', 'Greensboro', 826, '194', '27401'),
('Magnolia Blvd', 'St. Paul', 336, '195', '55101'),
('Walnut Path', 'Lincoln', 76, '196', '68501'),
('Poplar Street', 'Plano', 124, '197', '75023'),
('Birch Avenue', 'Jersey City', 156, '198', '07097'),
('Spruce Way', 'Chattanooga', 192, '199', '37401'),
('Chestnut Lane', 'Greensboro', 724, '200', '27401');

-- Dumping structure for table works.candidate
CREATE TABLE IF NOT EXISTS `candidate` (
  `id` bigint(20) NOT NULL AUTO_INCREMENT,
  `dob` date NOT NULL,
  `email` varchar(255) NOT NULL,
  `full_name` varchar(255) NOT NULL,
  `phone` varchar(15) NOT NULL,
  `address` bigint(20) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `UK_qfut8ruekode092nlkipgl09g` (`email`),
  UNIQUE KEY `UK_9i5yt1gvm0chg5e10qkns7tll` (`phone`),
  UNIQUE KEY `UK_m8qhlm4wu215gr34dhxp0dour` (`address`),
  CONSTRAINT `FKa8gnyyhbb2qnhp94grci1n0o9` FOREIGN KEY (`address`) REFERENCES `address` (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1 COLLATE=latin1_swedish_ci;

-- Data exporting was unselected.
INSERT INTO `candidate` (`dob`, `email`, `full_name`, `phone`, `address`) VALUES
('1990-01-01', 'john.doe1@example.com', 'John Doe', '1234567890', 1),
('1991-02-01', 'jane.smith2@example.com', 'Jane Smith', '1234567891', 2),
('1992-03-01', 'alice.jones3@example.com', 'Alice Jones', '1234567892', 3),
('1993-04-01', 'bob.brown4@example.com', 'Bob Brown', '1234567893', 4),
('1994-05-01', 'carol.white5@example.com', 'Carol White', '1234567894', 5),
('1995-06-01', 'dave.clark6@example.com', 'Dave Clark', '1234567895', 6),
('1996-07-01', 'eve.hall7@example.com', 'Eve Hall', '1234567896', 7),
('1997-08-01', 'frank.king8@example.com', 'Frank King', '1234567897', 8),
('1998-09-01', 'grace.lee9@example.com', 'Grace Lee', '1234567898', 9),
('1999-10-01', 'henry.wilson10@example.com', 'Henry Wilson', '1234567899', 10),
('1990-01-02', 'john.doe11@example.com', 'John Doe', '2234567890', 11),
('1991-02-02', 'jane.smith12@example.com', 'Jane Smith', '2234567891', 12),
('1992-03-02', 'alice.jones13@example.com', 'Alice Jones', '2234567892', 13),
('1993-04-02', 'bob.brown14@example.com', 'Bob Brown', '2234567893', 14),
('1994-05-02', 'carol.white15@example.com', 'Carol White', '2234567894', 15),
('1995-06-02', 'dave.clark16@example.com', 'Dave Clark', '2234567895', 16),
('1996-07-02', 'eve.hall17@example.com', 'Eve Hall', '2234567896', 17),
('1997-08-02', 'frank.king18@example.com', 'Frank King', '2234567897', 18),
('1998-09-02', 'grace.lee19@example.com', 'Grace Lee', '2234567898', 19),
('1999-10-02', 'henry.wilson20@example.com', 'Henry Wilson', '2234567899', 20),
('1990-01-03', 'john.doe21@example.com', 'John Doe', '3234567890', 21),
('1991-02-03', 'jane.smith22@example.com', 'Jane Smith', '3234567891', 22),
('1992-03-03', 'alice.jones23@example.com', 'Alice Jones', '3234567892', 23),
('1993-04-03', 'bob.brown24@example.com', 'Bob Brown', '3234567893', 24),
('1994-05-03', 'carol.white25@example.com', 'Carol White', '3234567894', 25),
('1995-06-03', 'dave.clark26@example.com', 'Dave Clark', '3234567895', 26),
('1996-07-03', 'eve.hall27@example.com', 'Eve Hall', '3234567896', 27),
('1997-08-03', 'frank.king28@example.com', 'Frank King', '3234567897', 28),
('1998-09-03', 'grace.lee29@example.com', 'Grace Lee', '3234567898', 29),
('1999-10-03', 'henry.wilson30@example.com', 'Henry Wilson', '3234567899', 30),
('1990-01-04', 'john.doe31@example.com', 'John Doe', '4234567890', 31),
('1991-02-04', 'jane.smith32@example.com', 'Jane Smith', '4234567891', 32),
('1992-03-04', 'alice.jones33@example.com', 'Alice Jones', '4234567892', 33),
('1993-04-04', 'bob.brown34@example.com', 'Bob Brown', '4234567893', 34),
('1994-05-04', 'carol.white35@example.com', 'Carol White', '4234567894', 35),
('1995-06-04', 'dave.clark36@example.com', 'Dave Clark', '4234567895', 36),
('1996-07-04', 'eve.hall37@example.com', 'Eve Hall', '4234567896', 37),
('1997-08-04', 'frank.king38@example.com', 'Frank King', '4234567897', 38),
('1998-09-04', 'grace.lee39@example.com', 'Grace Lee', '4234567898', 39),
('1999-10-04', 'henry.wilson40@example.com', 'Henry Wilson', '4234567899', 40),
('1990-01-05', 'john.doe41@example.com', 'John Doe', '5234567890', 41),
('1991-02-05', 'jane.smith42@example.com', 'Jane Smith', '5234567891', 42),
('1992-03-05', 'alice.jones43@example.com', 'Alice Jones', '5234567892', 43),
('1993-04-05', 'bob.brown44@example.com', 'Bob Brown', '5234567893', 44),
('1994-05-05', 'carol.white45@example.com', 'Carol White', '5234567894', 45),
('1995-06-05', 'dave.clark46@example.com', 'Dave Clark', '5234567895', 46),
('1996-07-05', 'eve.hall47@example.com', 'Eve Hall', '5234567896', 47),
('1997-08-05', 'frank.king48@example.com', 'Frank King', '5234567897', 48),
('1998-09-05', 'grace.lee49@example.com', 'Grace Lee', '5234567898', 49),
('1999-10-05', 'henry.wilson50@example.com', 'Henry Wilson', '5234567899', 50),
-- Tiếp tục chèn từ id 51 đến 100 --
('1990-01-06', 'john.doe51@example.com', 'John Doe', '6234567890', 51),
('1991-02-06', 'jane.smith52@example.com', 'Jane Smith', '6234567891', 52),
('1992-03-06', 'alice.jones53@example.com', 'Alice Jones', '6234567892', 53),
('1993-04-06', 'bob.brown54@example.com', 'Bob Brown', '6234567893', 54),
('1994-05-06', 'carol.white55@example.com', 'Carol White', '6234567894', 55),
('1995-06-06', 'dave.clark56@example.com', 'Dave Clark', '6234567895', 56),
('1996-07-06', 'eve.hall57@example.com', 'Eve Hall', '6234567896', 57),
('1997-08-06', 'frank.king58@example.com', 'Frank King', '6234567897', 58),
('1998-09-06', 'grace.lee59@example.com', 'Grace Lee', '6234567898', 59),
('1999-10-06', 'henry.wilson60@example.com', 'Henry Wilson', '6234567899', 60),
('1990-01-07', 'john.doe61@example.com', 'John Doe', '7234567890', 61),
('1991-02-07', 'jane.smith62@example.com', 'Jane Smith', '7234567891', 62),
('1992-03-07', 'alice.jones63@example.com', 'Alice Jones', '7234567892', 63),
('1993-04-07', 'bob.brown64@example.com', 'Bob Brown', '7234567893', 64),
('1994-05-07', 'carol.white65@example.com', 'Carol White', '7234567894', 65),
('1995-06-07', 'dave.clark66@example.com', 'Dave Clark', '7234567895', 66),
('1996-07-07', 'eve.hall67@example.com', 'Eve Hall', '7234567896', 67),
('1997-08-07', 'frank.king68@example.com', 'Frank King', '7234567897', 68),
('1998-09-07', 'grace.lee69@example.com', 'Grace Lee', '7234567898', 69),
('1999-10-07', 'henry.wilson70@example.com', 'Henry Wilson', '7234567899', 70),
('1990-01-08', 'john.doe71@example.com', 'John Doe', '8234567890', 71),
('1991-02-08', 'jane.smith72@example.com', 'Jane Smith', '8234567891', 72),
('1992-03-08', 'alice.jones73@example.com', 'Alice Jones', '8234567892', 73),
('1993-04-08', 'bob.brown74@example.com', 'Bob Brown', '8234567893', 74),
('1994-05-08', 'carol.white75@example.com', 'Carol White', '8234567894', 75),
('1995-06-08', 'dave.clark76@example.com', 'Dave Clark', '8234567895', 76),
('1996-07-08', 'eve.hall77@example.com', 'Eve Hall', '8234567896', 77),
('1997-08-08', 'frank.king78@example.com', 'Frank King', '8234567897', 78),
('1998-09-08', 'grace.lee79@example.com', 'Grace Lee', '8234567898', 79),
('1999-10-08', 'henry.wilson80@example.com', 'Henry Wilson', '8234567899', 80),
('1990-01-09', 'john.doe81@example.com', 'John Doe', '9234567890', 81),
('1991-02-09', 'jane.smith82@example.com', 'Jane Smith', '9234567891', 82),
('1992-03-09', 'alice.jones83@example.com', 'Alice Jones', '9234567892', 83),
('1993-04-09', 'bob.brown84@example.com', 'Bob Brown', '9234567893', 84),
('1994-05-09', 'carol.white85@example.com', 'Carol White', '9234567894', 85),
('1995-06-09', 'dave.clark86@example.com', 'Dave Clark', '9234567895', 86),
('1996-07-09', 'eve.hall87@example.com', 'Eve Hall', '9234567896', 87),
('1997-08-09', 'frank.king88@example.com', 'Frank King', '9234567897', 88),
('1998-09-09', 'grace.lee89@example.com', 'Grace Lee', '9234567898', 89),
('1999-10-09', 'henry.wilson90@example.com', 'Henry Wilson', '9234567899', 90),
('1990-01-10', 'john.doe91@example.com', 'John Doe', '1034567890', 91),
('1991-02-10', 'jane.smith92@example.com', 'Jane Smith', '1034567891', 92),
('1992-03-10', 'alice.jones93@example.com', 'Alice Jones', '1034567892', 93),
('1993-04-10', 'bob.brown94@example.com', 'Bob Brown', '1034567893', 94),
('1994-05-10', 'carol.white95@example.com', 'Carol White', '1034567894', 95),
('1995-06-10', 'dave.clark96@example.com', 'Dave Clark', '1034567895', 96),
('1996-07-10', 'eve.hall97@example.com', 'Eve Hall', '1034567896', 97),
('1997-08-10', 'frank.king98@example.com', 'Frank King', '1034567897', 98),
('1998-09-10', 'grace.lee99@example.com', 'Grace Lee', '1034567898', 99),
('1999-10-10', 'henry.wilson100@example.com', 'Henry Wilson', '1034567899', 100);

-- Dumping structure for table works.candidate_skill
CREATE TABLE IF NOT EXISTS `candidate_skill` (
  `more_infos` varchar(1000) DEFAULT NULL,
  `skill_level` tinyint(4) NOT NULL CHECK (`skill_level` between 0 and 2),
  `skill_id` bigint(20) NOT NULL,
  `can_id` bigint(20) NOT NULL,
  PRIMARY KEY (`can_id`,`skill_id`),
  KEY `FKb7cxhiqhcah7c20a2cdlvr1f8` (`skill_id`),
  CONSTRAINT `FKb0m5tm3fi0upa3b3kjx3vrlxs` FOREIGN KEY (`can_id`) REFERENCES `candidate` (`id`),
  CONSTRAINT `FKb7cxhiqhcah7c20a2cdlvr1f8` FOREIGN KEY (`skill_id`) REFERENCES `skill` (`skill_id`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1 COLLATE=latin1_swedish_ci;

-- Data exporting was unselected.
INSERT INTO `candidate_skill` (`more_infos`, `skill_level`, `skill_id`, `can_id`) VALUES
('Experienced in Java programming', 2, 1, 1),
('Basic knowledge of Python', 1, 2, 1),
('Expert in JavaScript', 2, 3, 2),
('Intermediate SQL skills', 1, 4, 2),
('Proficient in ReactJS', 2, 5, 3),
('Familiar with Spring Boot', 1, 6, 3),
('Advanced C++ developer', 2, 7, 4),
('Beginner in Docker', 0, 8, 4),
('Skilled in HTML and CSS', 2, 9, 5),
('Cloud computing enthusiast', 1, 10, 5),
('Machine learning projects', 2, 1, 6),
('Data analysis with Python', 1, 2, 6),
('Front-end frameworks expertise', 2, 3, 7),
('Database optimization', 2, 4, 7),
('Good knowledge of Angular', 1, 5, 8),
('Understanding of Kubernetes', 1, 6, 8),
('Competent in system design', 2, 7, 9),
('Knowledge of CI/CD pipelines', 1, 8, 9),
('User interface design skills', 2, 9, 10),
('Cloud infrastructure basics', 0, 10, 10),
('Backend API development', 2, 1, 11),
('Basic cybersecurity knowledge', 1, 2, 11),
('Advanced RESTful APIs', 2, 3, 12),
('Relational database management', 1, 4, 12),
('Basic PHP scripting', 0, 5, 13),
('Unit testing for Java', 1, 6, 13),
('Expert in microservices', 2, 7, 14),
('HTML5 and CSS3 mastery', 2, 9, 15),
('DevOps practices exposure', 1, 8, 16),
('Web design basics', 0, 10, 17),
('Full-stack development', 2, 1, 18),
('IoT projects experience', 1, 2, 18),
('Experienced in Vue.js', 2, 3, 19),
('Agile methodology basics', 0, 4, 19),
('Game development in Unity', 2, 7, 20),
('RPA (Robotic Process Automation)', 1, 8, 21),
('Cross-platform apps development', 2, 9, 22),
('Data visualization skills', 2, 10, 23),
('Cryptographic algorithms', 1, 1, 24),
('Docker container management', 2, 8, 25),
('Performance testing', 1, 6, 26),
('Big Data processing', 2, 10, 27),
('Frontend styling frameworks', 2, 9, 28),
('API gateway knowledge', 1, 3, 29),
('Basic MATLAB scripting', 0, 4, 30),
('Networking fundamentals', 1, 5, 31),
('IoT sensors and devices', 2, 6, 32),
('Experienced in Apache Kafka', 2, 7, 33),
('Understanding Linux commands', 1, 8, 34),
('Proficient with AWS', 2, 9, 35),
('Blockchain-based systems', 1, 10, 36),
('Embedded systems development', 2, 7, 37),
('Mobile app prototyping', 1, 5, 38),
('Version control systems (Git)', 2, 6, 39),
('Strong debugging skills', 2, 4, 40),
('AR/VR development projects', 1, 3, 41),
('Functional programming in Haskell', 1, 2, 42),
('AI model tuning', 2, 1, 43),
('Digital marketing basics', 0, 10, 44),
('SEO optimization knowledge', 1, 9, 45),
('Content management systems (CMS)', 2, 8, 46),
('E-commerce platform experience', 2, 5, 47),
('Cybersecurity threat detection', 1, 4, 48),
('Penetration testing skills', 2, 3, 49),
('Hardware troubleshooting', 0, 7, 50),
('API usage for AI/ML', 2, 10, 51),
('Experienced in Azure cloud', 2, 8, 52),
('Mobile-first web design', 2, 9, 53),
('Wireframe and mockup design', 1, 6, 54),
('Intermediate Ruby programming', 1, 5, 55),
('Virtualization technologies', 2, 7, 56),
('SaaS platform integrations', 1, 3, 57),
('Real-time systems management', 2, 4, 58),
('Beginner Elixir development', 0, 2, 59),
('High-performance computing', 2, 1, 60),
('Remote work collaboration tools', 1, 9, 61),
('UI/UX research', 1, 5, 62),
('System performance monitoring', 2, 3, 63),
('Familiar with Solidity', 0, 7, 64),
('In-depth analytics dashboards', 2, 10, 65),
('Functional test automation', 2, 6, 66),
('Dynamic programming solutions', 1, 4, 67),
('Digital signal processing', 2, 8, 68),
('Good knowledge of Scala', 1, 9, 69),
('CRM systems customization', 1, 5, 70),
('Linux kernel optimizations', 2, 7, 71),
('Hands-on RESTful API design', 2, 6, 72),
('Developing with Django', 1, 3, 73),
('Real-time communications (RTC)', 2, 2, 74),
('Basic robotics', 1, 10, 75),
('Best practices in DevSecOps', 2, 4, 76),
('Social media integration', 1, 5, 77),
('Integrating 3rd-party APIs', 2, 7, 78),
('Middleware programming', 1, 6, 79),
('Business logic design', 2, 8, 80),
('Optimization using NumPy', 1, 2, 81),
('ERP platform implementations', 2, 9, 82),
('Good practice in JavaFX', 1, 10, 83),
('Understanding of design systems', 1, 3, 84),
('High scalability services', 2, 4, 85),
('Good knowledge of GraphQL', 1, 5, 86),
('Data integrity management', 2, 7, 87),
('Mobile cloud synchronization', 2, 9, 88),
('End-to-end encryption', 1, 8, 89),
('IoT automation scripting', 1, 6, 90),
('Real-time language translation', 2, 4, 91),
('Accessibility compliance', 2, 5, 92),
('Good understanding of SAP', 2, 10, 93),
('Basic Android development', 1, 7, 94),
('Advanced statistics skills', 2, 1, 95),
('WebRTC signaling protocols', 2, 3, 96),
('Best practice configuration', 1, 2, 97),
('Knowledgeable in R', 2, 4, 98),
('Basic CSS animations', 0, 6, 99),
('Mobile optimization strategies', 1, 9, 100);

-- Dumping structure for table works.company
CREATE TABLE IF NOT EXISTS `company` (
  `comp_id` bigint(20) NOT NULL AUTO_INCREMENT,
  `about` varchar(2000) DEFAULT NULL,
  `email` varchar(255) NOT NULL,
  `comp_name` varchar(255) NOT NULL,
  `phone` varchar(255) NOT NULL,
  `web_url` varchar(255) DEFAULT NULL,
  `address` bigint(20) NOT NULL,
  PRIMARY KEY (`comp_id`),
  UNIQUE KEY `UK_rvp2hunsq4sgmpxe3a7i1ym3m` (`address`),
  CONSTRAINT `FKd5occp4cjwihejbxdbpvkp5tv` FOREIGN KEY (`address`) REFERENCES `address` (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1 COLLATE=latin1_swedish_ci;

-- Data exporting was unselected.
INSERT INTO `company` (`about`, `email`, `comp_name`, `phone`, `web_url`, `address`) VALUES
('Leading IT solutions provider specializing in cloud computing.', 'contact@cloudtech.com', 'CloudTech', '1234567890', 'www.cloudtech.com', 1),
('Innovative startup revolutionizing e-commerce platforms.', 'info@shopifyinnovate.com', 'Shopify Innovate', '1234567891', 'www.shopifyinnovate.com', 2),
('Global leader in renewable energy technology.', 'hello@greentech.com', 'GreenTech', '1234567892', 'www.greentech.com', 3),
('Pioneers in artificial intelligence and machine learning.', 'ai@aiworld.com', 'AI World', '1234567893', 'www.aiworld.com', 4),
('Experts in cybersecurity solutions for businesses.', 'security@cybersecure.com', 'CyberSecure', '1234567894', 'www.cybersecure.com', 5),
('Renowned automotive company leading the EV revolution.', 'contact@autotech.com', 'AutoTech', '1234567895', 'www.autotech.com', 6),
('Trusted software development and consultancy services.', 'services@codefactory.com', 'Code Factory', '1234567896', 'www.codefactory.com', 7),
('Manufacturing high-quality electronic components.', 'info@microcircuits.com', 'Micro Circuits', '1234567897', 'www.microcircuits.com', 8),
('Dedicated to delivering world-class healthcare products.', 'care@healthplus.com', 'Health Plus', '1234567898', 'www.healthplus.com', 9),
('Building infrastructure for smarter cities.', 'infra@urbanscape.com', 'UrbanScape', '1234567899', 'www.urbanscape.com', 10),
('Leading consultancy in data analytics and insights.', 'analytics@datapros.com', 'Data Pros', '1234567800', 'www.datapros.com', 11),
('Specialists in game development and virtual reality.', 'games@playhub.com', 'PlayHub Studios', '1234567801', 'www.playhub.com', 12),
('Providing financial solutions for startups and SMEs.', 'finance@venturehub.com', 'Venture Hub', '1234567802', 'www.venturehub.com', 13),
('Creators of high-performance sports equipment.', 'sales@sportzone.com', 'Sport Zone', '1234567803', 'www.sportzone.com', 14),
('Experts in logistics and supply chain management.', 'logistics@freightworld.com', 'Freight World', '1234567804', 'www.freightworld.com', 15),
('World-class publishers of educational resources.', 'education@learnershub.com', 'Learners Hub', '1234567805', 'www.learnershub.com', 16),
('Specializing in innovative fashion design and retail.', 'fashion@stylenow.com', 'StyleNow', '1234567806', 'www.stylenow.com', 17),
('Producers of premium organic food products.', 'info@greenharvest.com', 'Green Harvest', '1234567807', 'www.greenharvest.com', 18),
('Offering top-notch travel and hospitality services.', 'travel@globetrotters.com', 'GlobeTrotters', '1234567808', 'www.globetrotters.com', 19),
('Advanced research in biotechnology and genetics.', 'research@biogenetics.com', 'BioGenetics', '1234567809', 'www.biogenetics.com', 20),
('Leading provider of business analytics software solutions.', 'contact@analyticsoft.com', 'AnalyticSoft', '1234567810', 'www.analyticsoft.com', 21),
('Specializing in AI-driven marketing solutions.', 'info@marketbot.com', 'MarketBot', '1234567811', 'www.marketbot.com', 22),
('World leader in semiconductor manufacturing.', 'contact@semiconcorp.com', 'SemiconCorp', '1234567812', 'www.semiconcorp.com', 23),
('Providing innovative blockchain technology for enterprises.', 'support@blockchaininc.com', 'Blockchain Inc.', '1234567813', 'www.blockchaininc.com', 24),
('Top provider of virtual private networks (VPNs) and internet security solutions.', 'info@vpnsecure.com', 'VPN Secure', '1234567814', 'www.vpnsecure.com', 25),
('Global experts in 3D printing technology and product development.', 'contact@3dprintworks.com', '3D PrintWorks', '1234567815', 'www.3dprintworks.com', 26),
('Leaders in providing automated testing solutions for software and applications.', 'support@autotests.com', 'AutoTests', '1234567816', 'www.autotests.com', 27),
('Creative studio developing interactive media and digital experiences.', 'info@mediacreation.com', 'MediaCreation', '1234567817', 'www.mediacreation.com', 28),
('Providing cutting-edge cybersecurity for financial institutions.', 'security@finsecure.com', 'FinSecure', '1234567818', 'www.finsecure.com', 29),
('Leading edge in data storage solutions and cloud integration.', 'info@datacorp.com', 'DataCorp', '1234567819', 'www.datacorp.com', 30),
('Experts in the design and manufacturing of sustainable packaging solutions.', 'contact@greenpackaging.com', 'GreenPackaging', '1234567820', 'www.greenpackaging.com', 31),
('Innovating healthcare technologies for better patient outcomes.', 'healthcare@medsolutions.com', 'MedSolutions', '1234567821', 'www.medsolutions.com', 32),
('Smart home solutions, designing IoT devices for daily life.', 'support@smarthome.com', 'SmartHome', '1234567822', 'www.smarthome.com', 33),
('Global leader in telemedicine software and healthcare IT solutions.', 'info@telehealth.com', 'TeleHealth', '1234567823', 'www.telehealth.com', 34),
('Leading marketing platform specializing in influencer marketing solutions.', 'contact@influencemarketing.com', 'InfluenceMark', '1234567824', 'www.influencemarketing.com', 35),
('Provider of automated inventory management systems.', 'support@autoinventory.com', 'AutoInventory', '1234567825', 'www.autoinventory.com', 36),
('Top-tier solution provider in cloud computing services and IT infrastructure.', 'info@cloudservicepro.com', 'CloudServicePro', '1234567826', 'www.cloudservicepro.com', 37),
('Innovative mobile app solutions for small businesses.', 'contact@mobilesolutions.com', 'MobileSolutions', '1234567827', 'www.mobilesolutions.com', 38),
('Developing cutting-edge robotics for industrial automation.', 'info@roboticind.com', 'RoboticInd', '1234567828', 'www.roboticind.com', 39),
('Top-tier provider of big data analytics for enterprise solutions.', 'info@bigdataanalytics.com', 'BigDataAnalytics', '1234567829', 'www.bigdataanalytics.com', 40),
('Leading consulting firm offering IT transformation services.', 'consult@ittransform.com', 'ITTransform', '1234567830', 'www.ittransform.com', 41),
('Experts in the development of advanced materials for manufacturing industries.', 'contact@advancedmaterials.com', 'AdvancedMaterials', '1234567831', 'www.advancedmaterials.com', 42),
('Offering on-demand freelance solutions for IT and business development.', 'info@freelanceworks.com', 'FreelanceWorks', '1234567832', 'www.freelanceworks.com', 43),
('Delivering next-generation software for healthcare systems.', 'contact@healthtech.com', 'HealthTech', '1234567833', 'www.healthtech.com', 44),
('Specializing in cutting-edge AI solutions for education systems.', 'info@edutech.com', 'EduTech', '1234567834', 'www.edutech.com', 45),
('Leading provider of digital marketing and SEO services.', 'contact@seomaster.com', 'SEOMaster', '1234567835', 'www.seomaster.com', 46),
('Innovative solutions for the fintech industry, focusing on blockchain and AI.', 'info@fintechinnovate.com', 'FintechInnovate', '1234567836', 'www.fintechinnovate.com', 47),
('Top software provider for business process automation.', 'info@businessautomation.com', 'BusinessAutomation', '1234567837', 'www.businessautomation.com', 48),
('Leading experts in augmented reality and virtual reality development.', 'contact@arvrdev.com', 'ARVRDev', '1234567838', 'www.arvrdev.com', 49),
('Developers of premium video conferencing and collaboration tools.', 'info@collabtools.com', 'CollabTools', '1234567839', 'www.collabtools.com', 50),
('Cutting-edge solutions for voice recognition and AI-driven chatbots.', 'contact@voiceai.com', 'VoiceAI', '1234567840', 'www.voiceai.com', 51),
('Leading provider of customized enterprise software solutions for retail.', 'info@retailsoft.com', 'RetailSoft', '1234567841', 'www.retailsoft.com', 52),
('Specializing in green energy solutions and sustainable technologies.', 'contact@greenenergytech.com', 'GreenEnergyTech', '1234567842', 'www.greenenergytech.com', 53),
('Global leader in automotive parts and precision manufacturing.', 'support@autoparts.com', 'AutoPartsGlobal', '1234567843', 'www.autoparts.com', 54),
('Building innovative artificial intelligence platforms for business optimization.', 'contact@aiplatforms.com', 'AIPlatforms', '1234567844', 'www.aiplatforms.com', 55),
('Global leader in content creation and video production services.', 'contact@videomakers.com', 'VideoMakers', '1234567845', 'www.videomakers.com', 56),
('Innovative solutions for sustainable architecture and green building practices.', 'support@greenbuild.com', 'GreenBuild', '1234567846', 'www.greenbuild.com', 57),
('Delivering cloud-native solutions for enterprise IT operations.', 'contact@cloudnative.com', 'CloudNative', '1234567847', 'www.cloudnative.com', 58),
('Leading solutions provider for mobile and web app development.', 'info@mobwebdev.com', 'MobWebDev', '1234567848', 'www.mobwebdev.com', 59),
('Pioneers in drone technology for commercial applications.', 'contact@dronepioneers.com', 'DronePioneers', '1234567849', 'www.dronepioneers.com', 60),
('Creating sustainable food systems through advanced agricultural technology.', 'info@foodtech.com', 'FoodTech', '1234567850', 'www.foodtech.com', 61),
('Global leader in real estate development and urban planning.', 'contact@urbanrealty.com', 'UrbanRealty', '1234567851', 'www.urbanrealty.com', 62),
('Leading provider of blockchain-based supply chain management solutions.', 'contact@blockchainlogistics.com', 'BlockchainLogistics', '1234567852', 'www.blockchainlogistics.com', 63),
('Designing innovative software tools for legal professionals.', 'info@lawtech.com', 'LawTech', '1234567853', 'www.lawtech.com', 64),
('Top software provider for supply chain and logistics management.', 'support@logisticsolutions.com', 'LogisticsSolutions', '1234567854', 'www.logisticsolutions.com', 65),
('Innovative solutions for online learning and virtual classrooms.', 'contact@onlineteaching.com', 'OnlineTeaching', '1234567855', 'www.onlineteaching.com', 66),
('Creators of advanced digital signage solutions for retail and hospitality industries.', 'info@digitalsignage.com', 'DigitalSignage', '1234567856', 'www.digitalsignage.com', 67),
('Developing machine learning tools for predictive maintenance in manufacturing.', 'contact@predictivemaintenance.com', 'PredictiveMaintenance', '1234567857', 'www.predictivemaintenance.com', 68),
('Providing data-driven solutions for the financial services industry.', 'info@financialsolutions.com', 'FinancialSolutions', '1234567858', 'www.financialsolutions.com', 69),
('Leading edge in 3D visualization and rendering services for real estate and architecture.', 'contact@3dvisualization.com', '3DVisualization', '1234567859', 'www.3dvisualization.com', 70),
('Developing energy-efficient solutions for the automotive industry.', 'info@energyautosolutions.com', 'EnergyAutoSolutions', '1234567860', 'www.energyautosolutions.com', 71),
('Pioneers in the development of autonomous vehicle technology.', 'contact@autonomousvehicles.com', 'AutonomousVehicles', '1234567861', 'www.autonomousvehicles.com', 72),
('Creating next-generation software tools for video game development.', 'info@gamedevtools.com', 'GameDevTools', '1234567862', 'www.gamedevtools.com', 73),
('Experts in building and managing smart city solutions.', 'contact@smartcitysolutions.com', 'SmartCitySolutions', '1234567863', 'www.smartcitysolutions.com', 74),
('Top-tier provider of enterprise resource planning (ERP) software solutions.', 'support@erpsoftware.com', 'ERPSoftware', '1234567864', 'www.erpsoftware.com', 75),
('Building sustainable and eco-friendly products for the consumer market.', 'contact@ecoproducts.com', 'EcoProducts', '1234567865', 'www.ecoproducts.com', 76),
('Leading experts in personal finance management software and services.', 'info@personalfinance.com', 'PersonalFinance', '1234567866', 'www.personalfinance.com', 77),
('Providers of innovative biometric identification and authentication solutions.', 'contact@biometricsolutions.com', 'BiometricSolutions', '1234567867', 'www.biometricsolutions.com', 78),
('Cutting-edge mobile health apps for remote patient monitoring.', 'support@healthmonitoring.com', 'HealthMonitoring', '1234567868', 'www.healthmonitoring.com', 79),
('Leading provider of cybersecurity and anti-malware software solutions.', 'contact@cybersecure.com', 'CyberSecure', '1234567869', 'www.cybersecure.com', 80);
-- Dumping structure for table works.job
CREATE TABLE IF NOT EXISTS `job` (
  `job_id` bigint(20) NOT NULL AUTO_INCREMENT,
  `job_desc` varchar(2000) NOT NULL,
  `job_name` varchar(255) NOT NULL,
  `company` bigint(20) DEFAULT NULL,
  PRIMARY KEY (`job_id`),
  KEY `FKbaqlvluu78phmo9ld89um7wnm` (`company`),
  CONSTRAINT `FKbaqlvluu78phmo9ld89um7wnm` FOREIGN KEY (`company`) REFERENCES `company` (`comp_id`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1 COLLATE=latin1_swedish_ci;

-- Data exporting was unselected.
INSERT INTO `job` (`job_desc`, `job_name`, `company`) VALUES
('Manage and develop cloud infrastructure, oversee IT projects, and optimize the performance of cloud-based systems.', 'Cloud Engineer', 1),
('Develop innovative e-commerce platforms, ensure scalability and performance for growing businesses.', 'E-commerce Developer', 2),
('Design and implement renewable energy solutions, manage project teams to create green technologies.', 'Renewable Energy Specialist', 3),
('Develop and improve AI systems, create algorithms for machine learning models.', 'AI Engineer', 4),
('Create security protocols, conduct penetration testing, and implement network defenses.', 'Cybersecurity Expert', 5),
('Lead EV projects, manage production teams, and ensure the highest standards in electric vehicle development.', 'EV Project Manager', 6),
('Develop high-quality software, manage agile teams, and ensure timely delivery of software solutions.', 'Software Engineer', 7),
('Design and manufacture electronic components for consumer and industrial products.', 'Electronics Engineer', 8),
('Create health solutions using innovative technologies, manage healthcare product lifecycles.', 'Healthcare Product Manager', 9),
('Plan and design infrastructure projects, work on urban development and smart cities.', 'Infrastructure Planner', 10),
('Perform data analytics, extract insights for better business decision-making, and support clients.', 'Data Analyst', 11),
('Develop cutting-edge games, create VR and AR experiences, and improve user engagement.', 'Game Developer', 12),
('Create financial models, provide consulting services, and help companies grow.', 'Financial Consultant', 13),
('Design high-performance sports equipment, oversee manufacturing processes, and improve product quality.', 'Product Designer', 14),
('Manage logistics systems, oversee transportation networks, and ensure the efficiency of supply chains.', 'Logistics Manager', 15),
('Design and develop educational resources, work on publishing new learning materials.', 'Educational Content Developer', 16),
('Lead fashion projects, design clothing lines, and oversee the retail process.', 'Fashion Designer', 17),
('Manage food production, ensure product quality, and oversee the logistics of organic food distribution.', 'Food Production Manager', 18),
('Design and manage travel experiences, oversee hospitality projects, and ensure customer satisfaction.', 'Travel Experience Manager', 19),
('Work on cutting-edge biotech research, develop new genetic technologies, and manage research teams.', 'Biotech Researcher', 20),
('Work on web-based applications, collaborate with front-end teams, and optimize user experience.', 'Web Developer', 1),
('Develop mobile apps, work with cross-functional teams, and ensure smooth operation across platforms.', 'Mobile Application Developer', 2),
('Manage AI data systems, develop predictive models, and optimize machine learning processes.', 'AI Data Scientist', 3),
('Design cybersecurity systems, provide consulting services to businesses, and conduct risk assessments.', 'Cybersecurity Consultant', 4),
('Create and manage cloud computing solutions, optimize network systems, and lead cloud-based projects.', 'Cloud Architect', 5),
('Develop software for electric vehicles, enhance automation and systems integration.', 'EV Software Engineer', 6),
('Lead front-end web development, work on responsive designs, and implement modern web technologies.', 'Front-End Developer', 7),
('Manage large-scale IT projects, coordinate with cross-functional teams, and ensure timely delivery.', 'IT Project Manager', 8),
('Create and maintain embedded systems, oversee firmware development, and optimize hardware performance.', 'Embedded Systems Engineer', 9),
('Provide healthcare IT solutions, support healthcare systems, and integrate healthcare technologies.', 'Healthcare IT Specialist', 10),
('Plan and implement smart city projects, manage teams and resources, and oversee urban development.', 'Smart City Project Manager', 11),
('Create AI-driven solutions, work with big data, and develop machine learning models for businesses.', 'AI Solutions Architect', 12),
('Analyze business data, build predictive models, and assist in decision-making for companies.', 'Business Intelligence Analyst', 13),
('Design game environments, enhance user interaction, and collaborate with development teams to improve experiences.', 'Game Designer', 14),
('Manage financial operations, optimize accounting systems, and ensure compliance with regulations.', 'Finance Manager', 15),
('Oversee the design and manufacturing of sports gear, ensure quality control, and improve product features.', 'Sports Gear Designer', 16),
('Manage transportation logistics, create cost-effective solutions, and improve delivery systems.', 'Transportation Logistics Coordinator', 17),
('Create educational software, develop learning management systems, and support students and teachers.', 'Educational Software Engineer', 18),
('Work on clothing collections, ensure product quality, and collaborate with suppliers.', 'Apparel Designer', 19),
('Manage agricultural projects, oversee food production, and ensure quality standards in organic farming.', 'Agricultural Manager', 20),
('Plan and organize travel packages, create itineraries, and ensure a smooth travel experience for clients.', 'Travel Coordinator', 1),
('Develop biotechnology products, lead R&D projects, and oversee genetic testing technologies.', 'Biotechnology Product Manager', 2),
('Create AI models, improve language processing, and develop chatbots for various applications.', 'NLP Engineer', 3),
('Develop and maintain IT security infrastructure, manage firewalls and anti-malware systems.', 'Network Security Engineer', 4),
('Create software to manage EV charging stations, design vehicle-to-grid systems.', 'EV Infrastructure Engineer', 5),
('Lead the development of new software solutions, manage technical teams, and maintain agile workflows.', 'Software Development Manager', 6),
('Design and implement web applications, collaborate with back-end developers, and optimize for scalability.', 'Full Stack Developer', 7),
('Create and manage cloud-based storage systems, ensure data availability and security.', 'Cloud Storage Engineer', 8),
('Work on genetic sequencing projects, develop solutions for personalized medicine.', 'Genomics Researcher', 9),
('Oversee urban infrastructure development, create blueprints for sustainable cities.', 'Urban Planner', 10),
('Develop machine learning algorithms, work with large datasets, and deploy models in real-world applications.', 'Machine Learning Engineer', 11),
('Create and manage digital marketing campaigns, work with e-commerce platforms.', 'Digital Marketing Specialist', 12),
('Develop new gaming technologies, enhance game engine features, and improve graphics rendering.', 'Game Engine Developer', 13),
('Conduct financial analysis, create forecasting models, and provide financial consulting to clients.', 'Financial Analyst', 14),
('Design new sports technology, manage product innovation processes, and oversee product testing.', 'Sports Tech Innovator', 15),
('Create logistics software solutions, optimize warehouse management systems, and manage logistics projects.', 'Logistics Software Engineer', 16),
('Manage e-learning platforms, develop online courses, and optimize user engagement.', 'E-Learning Manager', 17),
('Create and manage content for fashion websites, work with design teams to develop product lines.', 'Fashion Content Manager', 18),
('Manage farm-to-table food distribution, ensure efficient food supply chain management.', 'Food Supply Chain Manager', 19),
('Plan and execute corporate travel strategies, manage business trip logistics for executives.', 'Corporate Travel Manager', 20),
('Lead research in regenerative medicine, develop treatments for aging and chronic conditions.', 'Regenerative Medicine Researcher', 1),
('Design systems for tracking and analyzing global supply chains, create real-time tracking tools.', 'Supply Chain Analyst', 2),
('Design and develop cutting-edge robotics systems, work on automation projects for manufacturing.', 'Robotics Engineer', 3),
('Develop financial software, automate accounting systems, and work with financial institutions.', 'Financial Software Developer', 4),
('Create educational tools for remote learning, improve access to education for underserved communities.', 'Remote Education Developer', 5),
('Lead the design of healthcare products, collaborate with medical professionals to create effective solutions.', 'Medical Product Designer', 6),
('Plan and build electric vehicle charging networks, collaborate with governments and businesses.', 'EV Charging Network Planner', 7),
('Research and design the next generation of VR gaming systems, develop immersive gaming experiences.', 'VR Gaming Systems Developer', 8),
('Create high-quality software for mobile healthcare applications, enhance patient experience.', 'Mobile Healthcare App Developer', 9),
('Create scalable cloud services, work on automation tools for cloud infrastructure.', 'Cloud Automation Engineer', 10),
('Develop data systems for clinical trials, work with medical data and healthcare providers.', 'Clinical Data Scientist', 11),
('Lead AI integration into smart devices, work with IoT teams to create intelligent environments.', 'IoT AI Engineer', 12),
('Develop and manage big data projects, work with large-scale distributed systems.', 'Big Data Engineer', 13),
('Analyze customer data, develop strategies to improve customer satisfaction and loyalty.', 'Customer Analytics Manager', 14),
('Create automation tools for large-scale manufacturing, oversee factory automation processes.', 'Factory Automation Engineer', 15),
('Manage real-time data systems, improve data transmission speeds, and enhance real-time processing.', 'Real-Time Data Engineer', 16),
('Create AI models for predictive analytics, deploy solutions to improve business decision-making.', 'Predictive Analytics Developer', 17),
('Lead research into renewable energy solutions, collaborate with tech startups for green projects.', 'Renewable Energy Consultant', 18),
('Design and implement AI solutions for healthcare, improve diagnosis accuracy with machine learning.', 'AI Healthcare Specialist', 19),
('Manage the development of fintech products, work with regulatory bodies to ensure compliance.', 'Fintech Product Manager', 20);

-- Dumping structure for table works.job_skill
CREATE TABLE IF NOT EXISTS `job_skill` (
  `more_infos` varchar(1000) DEFAULT NULL,
  `skill_level` tinyint(4) NOT NULL CHECK (`skill_level` between 0 and 2),
  `job_id` bigint(20) NOT NULL,
  `skill_id` bigint(20) NOT NULL,
  PRIMARY KEY (`job_id`,`skill_id`),
  KEY `FKj33qbbf3vk1lvhqpcosnh54u1` (`skill_id`),
  CONSTRAINT `FK9ix4wg520ii2gu2felxdhdup6` FOREIGN KEY (`job_id`) REFERENCES `job` (`job_id`),
  CONSTRAINT `FKj33qbbf3vk1lvhqpcosnh54u1` FOREIGN KEY (`skill_id`) REFERENCES `skill` (`skill_id`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1 COLLATE=latin1_swedish_ci;

-- Data exporting was unselected.
INSERT INTO `job_skill` (`more_infos`, `skill_level`, `job_id`, `skill_id`) VALUES
('Requires expertise in data analysis and machine learning.', 2, 1, 1),
('Knowledge of marketing analytics and campaign management.', 1, 2, 2),
('Requires proficiency in semiconductor manufacturing techniques.', 2, 3, 3),
('Requires experience with blockchain development and smart contracts.', 2, 4, 4),
('Knowledge in VPN technologies and cybersecurity protocols.', 1, 5, 5),
('Expertise in 3D printing and additive manufacturing.', 2, 6, 6),
('Proficient in automated software testing and continuous integration.', 1, 7, 7),
('Experience in media production and interactive media design.', 2, 8, 8),
('Expert in financial cybersecurity and fraud detection systems.', 2, 9, 9),
('Proficient in cloud storage and distributed computing.', 1, 10, 10),
('Experience in sustainable packaging design and materials.', 1, 11, 11),
('Knowledge of patient management systems and healthcare IT.', 2, 12, 12),
('Experience in AI-driven education tools and platforms.', 2, 13, 13),
('Proficient in SEO and digital content strategy.', 1, 14, 14),
('Knowledge of blockchain and fintech industry trends.', 2, 15, 15),
('Proficient in business process automation and workflow optimization.', 1, 16, 16),
('Experience with mobile app development for iOS and Android.', 1, 17, 17),
('Knowledge in industrial robotics and automation systems.', 2, 18, 18),
('Proficient in big data analytics and predictive modeling.', 2, 19, 19),
('Consulting experience in IT transformation and enterprise architecture.', 1, 20, 20),
('Expertise in the development of advanced materials and composites.', 2, 21, 1),
('Proficiency in managing on-demand freelancer platforms.', 1, 22, 2),
('Experience in healthcare software development and patient systems.', 1, 23, 3),
('Expertise in developing intelligent software for smart homes.', 2, 24, 4),
('Proficient in telemedicine platform design and implementation.', 1, 25, 5),
('Experience in influencer marketing and social media campaigns.', 2, 26, 6),
('Proficiency in inventory management and automation software.', 2, 27, 7),
('Expertise in cloud computing, SaaS, and infrastructure management.', 2, 28, 8),
('Experience in 3D printing for manufacturing and product design.', 1, 29, 9),
('Proficiency in cybersecurity measures for financial institutions.', 2, 30, 10),
('Expert in AI-driven marketing strategies and customer engagement.', 1, 31, 11),
('Proficiency in ERP system integration and optimization.', 2, 32, 12),
('Experience in mobile development and UI/UX design.', 1, 33, 13),
('Expertise in augmented reality and virtual reality applications.', 2, 34, 14),
('Proficiency in video conferencing solutions and collaboration tools.', 2, 35, 15),
('Expertise in AI-driven customer service and chatbot development.', 1, 36, 16),
('Knowledge of enterprise software systems and custom development.', 2, 37, 17),
('Proficiency in data-driven solutions for customer experience.', 2, 38, 18),
('Expertise in cloud-native architecture and serverless computing.', 1, 39, 19),
('Proficient in game development using Unity and Unreal Engine.', 1, 40, 20),
('Expertise in autonomous vehicle technologies and AI systems.', 2, 41, 1),
('Experience with drone technology and commercial applications.', 1, 42, 2),
('Proficiency in food technology and sustainable agriculture practices.', 1, 43, 3),
('Experience in real estate development and property management.', 2, 44, 4),
('Expertise in blockchain-based supply chain management.', 2, 45, 5),
('Proficiency in legal software development and legal tech tools.', 1, 46, 6),
('Experience in supply chain management software development.', 2, 47, 7),
('Expertise in online teaching platforms and virtual classrooms.', 1, 48, 8),
('Proficiency in digital signage and interactive advertising solutions.', 1, 49, 9),
('Experience in predictive maintenance using machine learning.', 2, 50, 10),
('Knowledge of data analytics for financial services and risk management.', 2, 51, 11),
('Proficiency in 3D visualization for architecture and real estate.', 1, 52, 12),
('Expertise in energy-efficient solutions for the automotive sector.', 2, 53, 13),
('Proficiency in autonomous vehicle development and AI applications.', 1, 54, 14),
('Experience in software tools for video game design and development.', 2, 55, 15),
('Expertise in smart city infrastructure and IoT solutions.', 1, 56, 16),
('Proficiency in ERP implementation and business resource planning.', 2, 57, 17),
('Experience in sustainable consumer product development and eco-friendly solutions.', 2, 58, 18),
('Proficiency in personal finance management and budgeting tools.', 1, 59, 19),
('Expertise in biometric security systems and authentication technology.', 2, 60, 20),
('Proficiency in mobile health applications for remote monitoring.', 1, 61, 1),
('Knowledge of anti-malware software development and cybersecurity.', 2, 62, 2),
('Expertise in real estate tech and property management software.', 1, 63, 3),
('Proficiency in blockchain integration for logistics management.', 2, 64, 4),
('Proficiency in legal tech and AI-powered legal solutions.', 2, 65, 5),
('Experience in supply chain logistics and automation software.', 1, 66, 6),
('Knowledge of online education systems and teaching technologies.', 2, 67, 7),
('Expertise in digital signage systems for retail and hospitality.', 1, 68, 8),
('Proficiency in predictive modeling and machine learning for manufacturing.', 2, 69, 9),
('Expertise in financial solutions and risk management systems.', 1, 70, 10),
('Proficiency in visualization techniques for architecture and design.', 2, 71, 11),
('Knowledge of energy-saving technologies for vehicles and automotive industry.', 1, 72, 12),
('Expertise in autonomous driving technology and AI-driven vehicles.', 2, 73, 13),
('Proficiency in game design and 3D modeling for video games.', 1, 74, 14),
('Expertise in smart city solutions and urban planning.', 2, 75, 15),
('Proficiency in ERP software solutions for businesses.', 1, 76, 16),
('Knowledge of eco-friendly product manufacturing and sustainable design.', 2, 77, 17),
('Expertise in personal finance and investment portfolio management.', 1, 78, 18),
('Proficiency in biometric data security and protection systems.', 2, 79, 19),
('Expertise in health monitoring and medical IoT devices.', 1, 80, 20),
('Proficiency in network security and data protection techniques.', 2, 81, 1),
('Experience in e-commerce and online sales platforms.', 1, 82, 2),
('Proficiency in cloud service development and cloud-based solutions.', 2, 83, 3),
('Expertise in blockchain applications for real estate and property management.', 1, 84, 4),
('Proficiency in software solutions for legal professionals.', 2, 85, 5),
('Expertise in supply chain solutions and inventory management.', 2, 86, 6),
('Proficiency in e-learning platform development and virtual classrooms.', 1, 87, 7),
('Experience in digital signage content management and delivery.', 2, 88, 8),
('Proficiency in machine learning and predictive analytics for manufacturing.', 1, 89, 9),
('Expertise in financial risk analysis and business strategy.', 2, 90, 10),
('Proficiency in 3D visualization for construction and real estate.', 1, 91, 11),
('Experience in sustainable automotive technologies and innovations.', 2, 92, 12),
('Proficiency in autonomous vehicle technologies and machine learning.', 1, 93, 13),
('Expertise in game development and interactive media.', 2, 94, 14),
('Experience in smart city technologies and IoT-based systems.', 1, 95, 15),
('Proficiency in ERP system design and business management solutions.', 2, 96, 16),
('Experience in creating eco-friendly consumer products and packaging.', 1, 97, 17),
('Proficiency in financial technologies and payment solutions.', 2, 98, 18),
('Expertise in biometric verification and security solutions.', 1, 99, 19),
('Proficiency in medical software and patient management systems.', 2, 100, 20);

-- Dumping structure for table works.skill
CREATE TABLE IF NOT EXISTS `skill` (
  `skill_id` bigint(20) NOT NULL AUTO_INCREMENT,
  `skill_description` varchar(255) DEFAULT NULL,
  `skill_name` varchar(255) DEFAULT NULL,
  `type` tinyint(4) DEFAULT NULL CHECK (`type` between 0 and 2),
  PRIMARY KEY (`skill_id`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1 COLLATE=LATIN1_SWEDISH_CI;

INSERT INTO `skill` (`skill_description`, `skill_name`, `type`) VALUES
('Proficiency in data analytics and statistical analysis.', 'Data Analysis', 0),
('Expertise in marketing strategies and campaign management.', 'Marketing', 1),
('Advanced knowledge of semiconductor manufacturing processes.', 'Semiconductor Manufacturing', 0),
('Experience with blockchain development and smart contracts.', 'Blockchain Development', 2),
('Advanced knowledge of cybersecurity and encryption methods.', 'Cybersecurity', 0),
('Experience with 3D printing technologies and applications.', '3D Printing', 2),
('Expertise in automation testing and continuous integration.', 'Automation Testing', 0),
('Proficiency in interactive media and game design.', 'Game Design', 1),
('Experience with financial fraud detection and anti-fraud systems.', 'Fraud Detection', 0),
('Expertise in cloud computing and distributed storage systems.', 'Cloud Computing', 1),
('Proficiency in sustainable design and eco-friendly materials.', 'Sustainable Design', 2),
('Experience with patient management systems in healthcare.', 'Healthcare IT', 0),
('Expertise in artificial intelligence and machine learning.', 'Artificial Intelligence', 2),
('Knowledge of SEO and digital content marketing.', 'SEO and Marketing', 1),
('Proficiency in business analytics and decision-making tools.', 'Business Analytics', 0),
('Expert in ERP system implementation and management.', 'ERP Systems', 2),
('Proficiency in mobile development for Android and iOS.', 'Mobile Development', 0),
('Expertise in industrial robotics and automation systems.', 'Industrial Robotics', 1),
('Knowledge of big data analytics and predictive modeling.', 'Big Data', 0),
('Consulting experience in IT transformation and enterprise architecture.', 'IT Consulting', 1),
('Expertise in the development of advanced materials and composites.', 'Material Science', 0),
('Proficiency in managing on-demand freelancer platforms.', 'Freelancer Platforms', 1),
('Experience in healthcare software development and patient systems.', 'Healthcare Software', 0),
('Expertise in intelligent software development for smart homes.', 'Smart Homes', 1),
('Proficiency in telemedicine platforms and patient monitoring systems.', 'Telemedicine', 2),
('Knowledge of influencer marketing and social media strategies.', 'Influencer Marketing', 1),
('Proficiency in inventory management and logistics software.', 'Inventory Management', 0),
('Expertise in cloud-native applications and serverless architecture.', 'Cloud-Native Applications', 2),
('Experience in 3D modeling for architecture and design.', '3D Modeling', 1),
('Proficiency in cybersecurity measures for financial institutions.', 'Financial Cybersecurity', 2),
('Expertise in digital advertising and interactive media.', 'Digital Advertising', 1),
('Knowledge of enterprise software and custom development.', 'Enterprise Software', 0),
('Proficiency in mobile game development and interactive apps.', 'Mobile Game Development', 1),
('Experience with augmented reality and virtual reality development.', 'AR/VR Development', 2),
('Proficiency in data visualization tools and techniques.', 'Data Visualization', 0),
('Knowledge of autonomous vehicle technology and machine learning.', 'Autonomous Vehicles', 1),
('Proficiency in enterprise architecture and IT strategy.', 'Enterprise Architecture', 0),
('Experience with sustainable automotive technology.', 'Automotive Technology', 2),
('Proficiency in game engines and 3D rendering techniques.', 'Game Engines', 1),
('Expertise in the Internet of Things and smart devices.', 'IoT', 2),
('Proficiency in predictive maintenance for manufacturing.', 'Predictive Maintenance', 0),
('Expert in AI-based customer service and automation.', 'AI Customer Service', 1),
('Experience with e-commerce platforms and digital sales strategies.', 'E-commerce', 0),
('Expertise in legal tech and software solutions for law firms.', 'Legal Tech', 1),
('Proficiency in blockchain-based supply chain management.', 'Blockchain Supply Chain', 0),
('Knowledge of virtual reality applications in healthcare.', 'VR in Healthcare', 2),
('Expertise in game development using Unity and Unreal Engine.', 'Game Development', 1),
('Proficiency in mobile application performance optimization.', 'Mobile App Optimization', 0),
('Experience in developing cloud-based SaaS products.', 'SaaS Development', 1),
('Proficiency in enterprise data management and reporting.', 'Data Management', 2),
('Expertise in online education platforms and LMS systems.', 'E-learning', 0),
('Proficiency in predictive analytics and machine learning.', 'Predictive Analytics', 2),
('Knowledge of digital health technologies and patient management systems.', 'Digital Health', 1),
('Expertise in renewable energy technologies and solutions.', 'Renewable Energy', 2),
('Proficiency in supply chain logistics and management.', 'Supply Chain Management', 0),
('Experience in 3D visualization for architecture and urban planning.', 'Urban Planning', 2),
('Expertise in biometric security systems and data protection.', 'Biometrics', 1),
('Proficiency in UX/UI design for digital products.', 'UX/UI Design', 0),
('Experience in software tools for educational purposes.', 'Educational Software', 2),
('Expertise in business process automation and optimization.', 'Business Automation', 1),
('Proficiency in data encryption and security algorithms.', 'Data Security', 2),
('Experience with smart city solutions and urban infrastructure.', 'Smart City Solutions', 0),
('Proficiency in game development and interactive media.', 'Interactive Media', 2),
('Expertise in advanced robotics and manufacturing technologies.', 'Advanced Robotics', 1),
('Experience in mobile app development for the healthcare sector.', 'Healthcare Apps', 2),
('Proficiency in renewable energy solutions for industrial use.', 'Industrial Energy Solutions', 0),
('Expertise in logistics and transport management systems.', 'Logistics Management', 1),
('Knowledge of supply chain optimization and data-driven solutions.', 'Supply Chain Optimization', 0),
('Proficiency in data science and machine learning algorithms.', 'Data Science', 2),
('Expertise in smart home technology and home automation systems.', 'Home Automation', 1),
('Proficiency in enterprise resource planning and business systems.', 'Business Systems', 0),
('Experience in AI-driven recommendation systems for e-commerce.', 'AI Recommendations', 1),
('Expertise in cybersecurity and risk management strategies.', 'Cybersecurity Risk Management', 2),
('Proficiency in cloud security and threat management.', 'Cloud Security', 0),
('Experience with online advertising and media buying platforms.', 'Digital Marketing', 1),
('Proficiency in predictive modeling and AI algorithms.', 'AI Algorithms', 2),
('Expertise in smart logistics and supply chain automation.', 'Smart Logistics', 0),
('Proficiency in natural language processing and AI for chatbots.', 'NLP for Chatbots', 1),
('Experience with autonomous robots and robotic systems.', 'Autonomous Robots', 2),
('Expertise in machine learning applications for healthcare.', 'ML for Healthcare', 0),
('Proficiency in creating mobile apps for fitness and health tracking.', 'Fitness Apps', 1),
('Knowledge of AI and its applications in business and tech.', 'AI in Business', 2),
('Experience with smart agriculture and farming solutions.', 'Smart Agriculture', 0),
('Proficiency in AI-based fraud detection systems.', 'AI Fraud Detection', 1),
('Expertise in project management and agile methodologies.', 'Project Management', 0),
('Proficiency in mobile app design for the education sector.', 'Education Apps', 1),
('Knowledge of renewable energy technologies and their implementation.', 'Energy Solutions', 2),
('Experience in customer service automation and chatbots.', 'Customer Service Automation', 1),
('Proficiency in building digital twins for urban planning and design.', 'Digital Twins', 0),
('Expertise in video game development and interactive entertainment.', 'Video Game Development', 2),
('Experience with voice recognition and AI-powered voice assistants.', 'Voice Recognition', 1),
('Proficiency in data mining and data processing techniques.', 'Data Mining', 0),
('Expertise in IoT technologies and connectivity solutions.', 'IoT Connectivity', 2),
('Proficiency in blockchain technology for decentralized finance.', 'DeFi Blockchain', 1),
('Experience in building and managing smart cities.', 'Smart City Management', 2),
('Proficiency in AI-based logistics optimization.', 'AI Logistics Optimization', 0),
('Expertise in digital forensics and data recovery.', 'Digital Forensics', 2),
('Proficiency in medical data management and health record systems.', 'Medical Data Management', 1),
('Knowledge of advanced manufacturing techniques and processes.', 'Advanced Manufacturing', 0),
('Experience in AR/VR applications in education and training.', 'AR/VR Education', 1),
('Expertise in data governance and compliance.', 'Data Governance', 0),
('Proficiency in AI for personalized learning platforms.', 'AI in Education', 1),
('Expertise in natural disaster prediction and emergency response systems.', 'Disaster Prediction', 2),
('Proficiency in wearable technology and IoT devices.', 'Wearable Technology', 0),
('Expertise in social media marketing and brand management.', 'Social Media Marketing', 1);

-- Data exporting was unselected.
CREATE TABLE IF NOT EXISTS `experience` (
    `exp_id` BIGINT(20) NOT NULL AUTO_INCREMENT,
    `company` VARCHAR(120) NOT NULL,
    `from_date` DATE NOT NULL,
    `to_date` DATE NOT NULL,
    `role` VARCHAR(100) NOT NULL,
    `work_desc` VARCHAR(400) NOT NULL,
    `can_id` BIGINT(20) NOT NULL,
    PRIMARY KEY (`exp_id`),
    CONSTRAINT `FK_experience_candidate` FOREIGN KEY (`can_id`) REFERENCES `candidate` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=latin1 COLLATE=latin1_swedish_ci;

/*!40103 SET TIME_ZONE=IFNULL(@OLD_TIME_ZONE, 'system') */;
/*!40101 SET SQL_MODE=IFNULL(@OLD_SQL_MODE, '') */;
/*!40014 SET FOREIGN_KEY_CHECKS=IFNULL(@OLD_FOREIGN_KEY_CHECKS, 1) */;
/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40111 SET SQL_NOTES=IFNULL(@OLD_SQL_NOTES, 1) */;
