spring.application.name=Week05_NguyenTanThaiDuong_21049641
spring.datasource.url=jdbc:mariadb://localhost:3306/works
spring.datasource.username=root
spring.datasource.password=root
spring.datasource.driver-class-name=org.mariadb.jdbc.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.thymeleaf.prefix=classpath:/templates/
spring.thymeleaf.suffix=.html
spring.thymeleaf.cache=false
# C?u hình email
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=duongnguyenqn132003@gmail.com
spring.mail.password=rqxoptearrsmvfin
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true